namespace YahooFinance.Client.Models;

internal class StockJsonObject
{
    public class Data
    {
        public double? _52WeekChange { get; set; }
        public double? SandP52WeekChange { get; set; }
        public string address1 { get; set; }
        public object algorithm { get; set; }
        public object annualHoldingsTurnover { get; set; }
        public object annualReportExpenseRatio { get; set; }
        public double? ask { get; set; }
        public int askSize { get; set; }
        public int averageDailyVolume10Day { get; set; }
        public int averageVolume { get; set; }
        public int averageVolume10days { get; set; }
        public double? beta { get; set; }
        public object beta3Year { get; set; }
        public double? bid { get; set; }
        public int bidSize { get; set; }
        public double? bookValue { get; set; }
        public object category { get; set; }
        public object circulatingSupply { get; set; }
        public string city { get; set; }
        public object coinMarketCapLink { get; set; }
        public List<object> companyOfficers { get; set; }
        public string country { get; set; }
        public string currency { get; set; }
        public decimal? currentPrice { get; set; }
        public double? currentRatio { get; set; }
        public int dateShortInterest { get; set; }
        public double? dayHigh { get; set; }
        public double? dayLow { get; set; }
        public double? debtToEquity { get; set; }
        public double? dividendRate { get; set; }
        public double? dividendYield { get; set; }
        public double? earningsGrowth { get; set; }
        public double? earningsQuarterlyGrowth { get; set; }
        public long ebitda { get; set; }
        public double? ebitdaMargins { get; set; }
        public double? enterpriseToEbitda { get; set; }
        public double? enterpriseToRevenue { get; set; }
        public long enterpriseValue { get; set; }
        public int exDividendDate { get; set; }
        public string exchange { get; set; }
        public string exchangeTimezoneName { get; set; }
        public string exchangeTimezoneShortName { get; set; }
        public object expireDate { get; set; }
        public double? fiftyDayAverage { get; set; }
        public double? fiftyTwoWeekHigh { get; set; }
        public double? fiftyTwoWeekLow { get; set; }
        public string financialCurrency { get; set; }
        public object fiveYearAverageReturn { get; set; }
        public double? fiveYearAvgDividendYield { get; set; }
        public long floatShares { get; set; }
        public double? forwardEps { get; set; }
        public double? forwardPE { get; set; }
        public long freeCashflow { get; set; }
        public object fromCurrency { get; set; }
        public int fullTimeEmployees { get; set; }
        public object fundFamily { get; set; }
        public object fundInceptionDate { get; set; }
        public string gmtOffSetMilliseconds { get; set; }
        public double? grossMargins { get; set; }
        public long grossProfits { get; set; }
        public double? heldPercentInsiders { get; set; }
        public double? heldPercentInstitutions { get; set; }
        public int impliedSharesOutstanding { get; set; }
        public string industry { get; set; }
        public bool isEsgPopulated { get; set; }
        public object lastCapGain { get; set; }
        public int lastDividendDate { get; set; }
        public double? lastDividendValue { get; set; }
        public int lastFiscalYearEnd { get; set; }
        public object lastMarket { get; set; }
        public int lastSplitDate { get; set; }
        public string lastSplitFactor { get; set; }
        public object legalType { get; set; }
        public string logo_url { get; set; }
        public string longBusinessSummary { get; set; }
        public string longName { get; set; }
        public string market { get; set; }
        public long marketCap { get; set; }
        public int maxAge { get; set; }
        public object maxSupply { get; set; }
        public string messageBoardId { get; set; }
        public object morningStarOverallRating { get; set; }
        public object morningStarRiskRating { get; set; }
        public int mostRecentQuarter { get; set; }
        public object navPrice { get; set; }
        public long netIncomeToCommon { get; set; }
        public int nextFiscalYearEnd { get; set; }
        public int numberOfAnalystOpinions { get; set; }
        public double? open { get; set; }
        public object openInterest { get; set; }
        public long operatingCashflow { get; set; }
        public double? operatingMargins { get; set; }
        public double? payoutRatio { get; set; }
        public double? pegRatio { get; set; }
        public string phone { get; set; }
        public double? preMarketPrice { get; set; }
        public double? previousClose { get; set; }
        public int priceHint { get; set; }
        public double? priceToBook { get; set; }
        public double? priceToSalesTrailing12Months { get; set; }
        public double? profitMargins { get; set; }
        public double? quickRatio { get; set; }
        public string quoteType { get; set; }
        public string recommendationKey { get; set; }
        public double? recommendationMean { get; set; }
        public double? regularMarketDayHigh { get; set; }
        public double? regularMarketDayLow { get; set; }
        public double? regularMarketOpen { get; set; }
        public double? regularMarketPreviousClose { get; set; }
        public double? regularMarketPrice { get; set; }
        public int regularMarketVolume { get; set; }
        public double? returnOnAssets { get; set; }
        public double? returnOnEquity { get; set; }
        public double? revenueGrowth { get; set; }
        public double? revenuePerShare { get; set; }
        public object revenueQuarterlyGrowth { get; set; }
        public string sector { get; set; }
        public long sharesOutstanding { get; set; }
        public double? sharesPercentSharesOut { get; set; }
        public int sharesShort { get; set; }
        public int sharesShortPreviousMonthDate { get; set; }
        public int sharesShortPriorMonth { get; set; }
        public string shortName { get; set; }
        public double? shortPercentOfFloat { get; set; }
        public double? shortRatio { get; set; }
        public object startDate { get; set; }
        public string state { get; set; }
        public object strikePrice { get; set; }
        public string symbol { get; set; }
        public int targetHighPrice { get; set; }
        public int targetLowPrice { get; set; }
        public double? targetMeanPrice { get; set; }
        public int targetMedianPrice { get; set; }
        public object threeYearAverageReturn { get; set; }
        public object toCurrency { get; set; }
        public object totalAssets { get; set; }
        public long totalCash { get; set; }
        public double? totalCashPerShare { get; set; }
        public long totalDebt { get; set; }
        public long totalRevenue { get; set; }
        public bool tradeable { get; set; }
        public double? trailingAnnualDividendRate { get; set; }
        public double? trailingAnnualDividendYield { get; set; }
        public double? trailingEps { get; set; }
        public double? trailingPE { get; set; }
        public double? trailingPegRatio { get; set; }
        public double? twoHundredDayAverage { get; set; }
        public int volume { get; set; }
        public object volume24Hr { get; set; }
        public object volumeAllCurrencies { get; set; }
        public string website { get; set; }
        public object yield { get; set; }
        public object ytdReturn { get; set; }
        public string zip { get; set; }
    }

    public class Root
    {
        public Data Data { get; set; }
        public string Message { get; set; }
        public int Status { get; set; }
    }
}

