namespace YahooFinance.Client.Models;

public class StockInfoJsonObject
{
    public string Address1 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Website { get; set; }
    public string Industry { get; set; }
    public string IndustryKey { get; set; }
    public string IndustryDisp { get; set; }
    public string Sector { get; set; }
    public string SectorKey { get; set; }
    public string SectorDisp { get; set; }
    public string LongBusinessSummary { get; set; }
    public int FullTimeEmployees { get; set; }
    public List<CompanyOfficer> CompanyOfficers { get; set; }
    public int AuditRisk { get; set; }
    public int BoardRisk { get; set; }
    public int CompensationRisk { get; set; }
    public int ShareHolderRightsRisk { get; set; }
    public int OverallRisk { get; set; }
    public long GovernanceEpochDate { get; set; }
    public long CompensationAsOfEpochDate { get; set; }
    public string IrWebsite { get; set; }
    public int MaxAge { get; set; }
    public int PriceHint { get; set; }
    public decimal PreviousClose { get; set; }
    public decimal Open { get; set; }
    public decimal DayLow { get; set; }
    public decimal DayHigh { get; set; }
    public decimal RegularMarketPreviousClose { get; set; }
    public decimal RegularMarketOpen { get; set; }
    public decimal RegularMarketDayLow { get; set; }
    public decimal RegularMarketDayHigh { get; set; }
    public decimal DividendRate { get; set; }
    public decimal DividendYield { get; set; }
    public long ExDividendDate { get; set; }
    public decimal PayoutRatio { get; set; }
    public decimal FiveYearAvgDividendYield { get; set; }
    public decimal Beta { get; set; }
    public decimal TrailingPE { get; set; }
    public decimal ForwardPE { get; set; }
    public long Volume { get; set; }
    public long RegularMarketVolume { get; set; }
    public long AverageVolume { get; set; }
    public long AverageVolume10days { get; set; }
    public long AverageDailyVolume10Day { get; set; }
    public decimal Bid { get; set; }
    public decimal Ask { get; set; }
    public int BidSize { get; set; }
    public int AskSize { get; set; }
    public long MarketCap { get; set; }
    public decimal FiftyTwoWeekLow { get; set; }
    public decimal FiftyTwoWeekHigh { get; set; }
    public decimal PriceToSalesTrailing12Months { get; set; }
    public decimal FiftyDayAverage { get; set; }
    public decimal TwoHundredDayAverage { get; set; }
    public decimal TrailingAnnualDividendRate { get; set; }
    public decimal TrailingAnnualDividendYield { get; set; }
    public string Currency { get; set; }
    public long EnterpriseValue { get; set; }
    public decimal ProfitMargins { get; set; }
    public long FloatShares { get; set; }
    public long SharesOutstanding { get; set; }
    public long SharesShort { get; set; }
    public long SharesShortPriorMonth { get; set; }
    public long SharesShortPreviousMonthDate { get; set; }
    public long DateShortInterest { get; set; }
    public decimal SharesPercentSharesOut { get; set; }
    public decimal HeldPercentInsiders { get; set; }
    public decimal HeldPercentInstitutions { get; set; }
    public decimal ShortRatio { get; set; }
    public decimal ShortPercentOfFloat { get; set; }
    public long ImpliedSharesOutstanding { get; set; }
    public decimal BookValue { get; set; }
    public decimal PriceToBook { get; set; }
    public long LastFiscalYearEnd { get; set; }
    public long NextFiscalYearEnd { get; set; }
    public long MostRecentQuarter { get; set; }
    public decimal EarningsQuarterlyGrowth { get; set; }
    public long NetIncomeToCommon { get; set; }
    public decimal TrailingEps { get; set; }
    public decimal ForwardEps { get; set; }
    public decimal PegRatio { get; set; }
    public string LastSplitFactor { get; set; }
    public long LastSplitDate { get; set; }
    public decimal EnterpriseToRevenue { get; set; }
    public decimal EnterpriseToEbitda { get; set; }
    public decimal FiftyTwoWeekChange { get; set; }
    public decimal SandP52WeekChange { get; set; }
    public decimal LastDividendValue { get; set; }
    public long LastDividendDate { get; set; }
    public string Exchange { get; set; }
    public string QuoteType { get; set; }
    public string Symbol { get; set; }
    public string UnderlyingSymbol { get; set; }
    public string ShortName { get; set; }
    public string LongName { get; set; }
    public long FirstTradeDateEpochUtc { get; set; }
    public string TimeZoneFullName { get; set; }
    public string TimeZoneShortName { get; set; }
    public string Uuid { get; set; }
    public string MessageBoardId { get; set; }
    public long GmtOffSetMilliseconds { get; set; }
    public double CurrentPrice { get; set; }
    public decimal TargetHighPrice { get; set; }
    public decimal TargetLowPrice { get; set; }
    public decimal TargetMeanPrice { get; set; }
    public decimal TargetMedianPrice { get; set; }
    public decimal RecommendationMean { get; set; }
    public string RecommendationKey { get; set; }
    public int NumberOfAnalystOpinions { get; set; }
    public long TotalCash { get; set; }
    public decimal TotalCashPerShare { get; set; }
    public long Ebitda { get; set; }
    public long TotalDebt { get; set; }
    public decimal QuickRatio { get; set; }
    public decimal CurrentRatio { get; set; }
    public long TotalRevenue { get; set; }
    public decimal DebtToEquity { get; set; }
    public decimal RevenuePerShare { get; set; }
    public decimal ReturnOnAssets { get; set; }
    public decimal ReturnOnEquity { get; set; }
    public long FreeCashflow { get; set; }
    public long OperatingCashflow { get; set; }
    public decimal EarningsGrowth { get; set; }
    public decimal RevenueGrowth { get; set; }
    public decimal GrossMargins { get; set; }
    public decimal EbitdaMargins { get; set; }
    public decimal OperatingMargins { get; set; }
    public string FinancialCurrency { get; set; }
    public decimal TrailingPegRatio { get; set; }
}

public class CompanyOfficer
{
    public int MaxAge { get; set; }
    public string Name { get; set; }
    public int? Age { get; set; }
    public string Title { get; set; }
    public int? YearBorn { get; set; }
    public int FiscalYear { get; set; }
    public long TotalPay { get; set; }
    public long ExercisedValue { get; set; }
    public long UnexercisedValue { get; set; }
}